#!/usr/bin/env python3
# =====================================================================
# audit_website_freshness.py v1.0
#
# Sweeps Website/data/*.js + Website/*.html and produces a coverage
# report classifying each file as:
#   AUTO       - regenerated by some snapshot-pipeline tool
#   MANUAL     - hand-curated; @MANUAL_OVERRIDE sentinel
#   DERIVED    - hand-curated narrative + auto overlay (toe.js + injected)
#   UNKNOWN    - no sentinel; needs classification
#
# For MANUAL files, also records last-modified date vs canonical
# source-of-truth (where applicable) so operator can spot stale items.
#
# Output: Docs/status/WEBSITE-FRESHNESS-AUDIT.md
#
# Hooked into snapshot.ps1 step 2.6 (after publish-papers, before
# verify-website) so every snapshot includes a freshness audit.
# =====================================================================
from __future__ import annotations

import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
WEBSITE   = REPO_ROOT / "Website"
OUT_MD    = REPO_ROOT / "Docs" / "status" / "WEBSITE-FRESHNESS-AUDIT.md"

# Known auto-generators (filename -> generator)
KNOWN_AUTO_GENERATORS = {
    "papers_pdf_index.js":         "Codes/tools/publish_papers.py",
    "papers_math_dependencies.js": "Codes/tools/extract_paper_dependencies.py",
    "status_pillar_tiers.js":      "Codes/tools/sync_toe_from_status.py",
    "code.js":                     "Codes/tools/generate_website.py",
    "code-old.js":                 "Codes/tools/generate_website.py",
    "history.js":                  "Codes/tools/generate_website.py",
    "math-notes.js":               "Codes/tools/generate_website.py",
    "records.js":                  "Codes/tools/generate_website.py",
    "results.js":                  "Codes/tools/generate_website.py",
}

# Known manual files where canonical source-of-truth is internal narrative
KNOWN_MANUAL = {
    "index.js":   "Landing-page narrative (hand-curated)",
    "site.js":    "Site chrome / navigation menu (hand-curated)",
    "status.js":  "Source-of-truth for 11-pillar T-tier scoreboard",
    "theory.js":  "Theoretical-framework narrative",
    "papers.js":  "Curated proof-archive index (paper-by-paper)",
    "toe.js":     "6-Stage TOE roadmap narrative (overlay auto-synced)",
}


def classify_js(path: Path) -> Tuple[str, str]:
    """Return (status, note) for a Website/data/*.js file."""
    try:
        head = path.read_text(encoding="utf-8", errors="replace")[:2000]
    except OSError:
        return ("ERROR", "could not read")
    name = path.name
    if "AUTO-GENERATED" in head or "auto-generated" in head:
        gen = KNOWN_AUTO_GENERATORS.get(name, "(generator unknown)")
        return ("AUTO", f"by {gen}")
    if "@MANUAL_OVERRIDE" in head or "hand-curated" in head:
        note = KNOWN_MANUAL.get(name, "manual file")
        return ("MANUAL", note)
    return ("UNKNOWN", "no sentinel header found")


def classify_html(path: Path) -> Tuple[str, str]:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ("ERROR", "could not read")
    has_nav      = "tect-nav.js" in text
    has_render   = "tect-render.js" in text
    has_overlay  = "TECT-AUTO-TOE-OVERLAY" in text
    flags = []
    if has_nav:    flags.append("nav-injected")
    if has_render: flags.append("chrome-rendered")
    if has_overlay: flags.append("toe-overlay")
    return ("HTML", ", ".join(flags) or "no shared scripts")


def main() -> int:
    print(" TECT website-freshness audit v1.0")
    js_results: List[Tuple[str, str, str, int]] = []
    for js in sorted((WEBSITE / "data").glob("*.js")):
        status, note = classify_js(js)
        size_kb = js.stat().st_size // 1024
        js_results.append((js.name, status, note, size_kb))
    html_results: List[Tuple[str, str, str, int]] = []
    for h in sorted(WEBSITE.glob("*.html")):
        status, note = classify_html(h)
        size_kb = h.stat().st_size // 1024
        html_results.append((h.name, status, note, size_kb))

    n_auto    = sum(1 for _, s, *_ in js_results if s == "AUTO")
    n_manual  = sum(1 for _, s, *_ in js_results if s == "MANUAL")
    n_unknown = sum(1 for _, s, *_ in js_results if s == "UNKNOWN")
    n_error   = sum(1 for _, s, *_ in js_results if s == "ERROR")
    print(f"[audit] Website/data/*.js classification: AUTO={n_auto} "
          f"MANUAL={n_manual} UNKNOWN={n_unknown} ERROR={n_error}")
    n_pages = len(html_results)
    n_with_nav = sum(1 for _, _, n, _ in html_results if "nav-injected" in n)
    print(f"[audit] Website/*.html: {n_pages} pages, "
          f"{n_with_nav} have back-to-top nav injected")

    # Markdown report
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    lines = []
    lines.append("<!-- AUTO-GENERATED by Codes/tools/audit_website_freshness.py - DO NOT EDIT. -->")
    lines.append("# Website Freshness Audit")
    lines.append("")
    lines.append(f"**Generated**: `{now}`")
    lines.append("")
    lines.append("## 1. Website/data/*.js classification")
    lines.append("")
    lines.append(f"AUTO: {n_auto} &middot; MANUAL: {n_manual} "
                 f"&middot; UNKNOWN: {n_unknown} &middot; ERROR: {n_error}")
    lines.append("")
    lines.append("| File | Status | KB | Note |")
    lines.append("|---|---|---:|---|")
    for name, status, note, kb in js_results:
        emoji = {"AUTO": "[A]", "MANUAL": "[M]", "UNKNOWN": "[?]",
                 "ERROR": "[E]"}.get(status, "[ ]")
        lines.append(f"| `{name}` | {emoji} {status} | {kb} | {note} |")
    lines.append("")
    lines.append("## 2. Website/*.html navigation coverage")
    lines.append("")
    lines.append(f"{n_pages} HTML pages, {n_with_nav} with shared back-to-top nav.")
    lines.append("")
    lines.append("| File | KB | Shared scripts |")
    lines.append("|---|---:|---|")
    for name, _status, note, kb in html_results:
        lines.append(f"| `{name}` | {kb} | {note} |")
    lines.append("")
    lines.append("## 3. Snapshot-pipeline coverage")
    lines.append("")
    lines.append("Tools that auto-update Website/data on every snapshot:")
    lines.append("")
    lines.append("| Tool | Output | Step |")
    lines.append("|---|---|---|")
    lines.append("| `Codes/tools/generate_website.py` | `code.js`, `code-old.js`, `history.js`, `math-notes.js`, `records.js`, `results.js` | step 2 |")
    lines.append("| `Codes/tools/sync_toe_from_status.py` | `status_pillar_tiers.js` + `toe.html` overlay | step 2.4 |")
    lines.append("| `Codes/tools/extract_paper_dependencies.py` | `papers_math_dependencies.js` + `Docs/status/PAPER-MATH-DEPENDENCIES.md` | step 2.5a |")
    lines.append("| `Codes/tools/publish_papers.py` | `papers_pdf_index.js` + `Github/assets/papers/` | step 2.5b |")
    lines.append("| `Codes/tools/audit_website_freshness.py` (this) | `Docs/status/WEBSITE-FRESHNESS-AUDIT.md` | step 2.6 |")
    lines.append("")
    lines.append("Files NOT auto-updated (manual edit required):")
    lines.append("")
    lines.append("| File | Reason |")
    lines.append("|---|---|")
    for name, status, note, _ in js_results:
        if status == "MANUAL":
            lines.append(f"| `Website/data/{name}` | {note} |")
    lines.append("")

    try:
        OUT_MD.parent.mkdir(parents=True, exist_ok=True)
        OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"[audit] wrote {OUT_MD.relative_to(REPO_ROOT)}")
    except OSError as exc:
        print(f"[audit] ERROR: {exc}", file=sys.stderr)
        return 1
    print("[audit] OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
