#!/usr/bin/env python3
# =====================================================================
# github_sync_curate.py — Layer 1 of GitHub publish pipeline (offline).
#
# Binding policy: Docs/policy/GITHUB_SYNC_POLICY.md (2026-04-29).
# Companion: github_sync_push.py (Layer 2, network + credentials).
#
# Purpose
# -------
# After a successful website regeneration + verifier pass, curate the
# subset of repository content that is appropriate for the *public*
# GitHub mirror, and write it into Github/. The Github/ folder is
# isolated from the main repo (.gitignore'd) and is intended to be the
# working tree of a separate public repository.
#
# Invariants (DO NOT VIOLATE)
#   I1  No network calls. This step MUST work fully offline.
#   I2  Idempotent. Running curate twice in a row produces the same
#       Github/ tree.
#   I3  Never touches Github/.git/ — the push layer owns git state.
#   I4  English-only output. The CLAUDE.md s5.1 / OUTPUT_LANGUAGE_POLICY.md
#       rule applies recursively.
#   I5  Auto-generated files carry an explicit AUTO-GENERATED sentinel
#       so a human editor knows not to hand-edit them.
#
# CLI
# ---
#   python -u Codes/tools/github_sync_curate.py            # build Github/
#   python -u Codes/tools/github_sync_curate.py --check    # dry-run, list deltas
#   python -u Codes/tools/github_sync_curate.py --clean    # wipe Github/ first
#
# Author: Jusang Lee + collaboration (2026-04-29).
# =====================================================================

from __future__ import annotations

import argparse
import filecmp
import hashlib
import json
import os
import re
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
WEBSITE = REPO_ROOT / "Website"
DOCS = REPO_ROOT / "Docs"
TARGET = REPO_ROOT / "Github"
TARGET_DOCS = TARGET / "docs"

CHANGELOG = REPO_ROOT / "CHANGELOG.md"
TOE_FACT_SHEET = DOCS / "status" / "TOE-FACT-SHEET.md"
INDEX_NARRATIVE = WEBSITE / "data" / "_narrative" / "index_subtitle.md"
LATEST_STATUS = WEBSITE / "data" / "_narrative" / "_latest_status_2026-04-29.md"

AUTO_SENTINEL_MD = (
    "<!-- AUTO-GENERATED by Codes/tools/github_sync_curate.py -- DO NOT EDIT BY HAND. -->\n"
    "<!-- Regenerate via: python -u Codes/tools/github_sync_curate.py -->\n\n"
)

AUTO_SENTINEL_YAML = (
    "# AUTO-GENERATED by Codes/tools/github_sync_curate.py -- DO NOT EDIT BY HAND.\n"
    "# Regenerate via: python -u Codes/tools/github_sync_curate.py\n\n"
)

# Mirror policy descriptor: Codes/config/mirror.json. Read at curate time;
# operator-curated exclusions in `exclude_from_mirror.active_v1_0` are
# pruned from Github/. Defaults to empty list -> current behaviour preserved.
MIRROR_CONFIG = REPO_ROOT / "Codes" / "config" / "mirror.json"


def _load_mirror_excludes() -> list[str]:
    """Read Codes/config/mirror.json and return the active exclude list.
    Returns empty list if the file is absent / malformed (fail-safe)."""
    if not MIRROR_CONFIG.exists():
        return []
    try:
        cfg = json.loads(MIRROR_CONFIG.read_text(encoding="utf-8"))
        excl = cfg.get("exclude_from_mirror", {}).get("active_v1_0", [])
        return [str(x) for x in excl if isinstance(x, str)]
    except (OSError, json.JSONDecodeError):
        return []


# ---------------------------------------------------------------------
# Section A. Stats & low-level filesystem helpers
# ---------------------------------------------------------------------
class CurateStats:
    """Lightweight delta tracker so the operator sees what changed."""

    def __init__(self) -> None:
        self.added: list[str] = []
        self.modified: list[str] = []
        self.unchanged: int = 0
        self.removed: list[str] = []
        self.skipped_dotgit: int = 0


def _file_hash(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _ensure_dir(p: Path) -> None:
    p.mkdir(parents=True, exist_ok=True)


def _write_text_idempotent(target: Path, content: str, stats: CurateStats,
                           rel_label: str, *, dry_run: bool) -> None:
    """Write `content` to `target`, comparing first to suppress noise.

    Always uses LF line-endings + UTF-8 to keep the public mirror diff
    stable across operator OS (the .gitattributes of the *public* repo
    is the operator's call; here we just normalise on emission)."""
    new_bytes = content.encode("utf-8")
    if target.exists():
        try:
            old_bytes = target.read_bytes()
        except OSError:
            old_bytes = None
        if old_bytes == new_bytes:
            stats.unchanged += 1
            return
        if not dry_run:
            target.write_bytes(new_bytes)
        stats.modified.append(rel_label)
        return
    if not dry_run:
        _ensure_dir(target.parent)
        target.write_bytes(new_bytes)
    stats.added.append(rel_label)


def _copy_file_idempotent(src: Path, dst: Path, stats: CurateStats,
                          rel_label: str, *, dry_run: bool) -> None:
    """Copy `src` to `dst` only if size+mtime differ (rsync-style fast skip).

    `shutil.copy2` preserves mtime + permissions, so after the first copy
    the destination has identical (size, mtime) to source. We rely on
    that for the fast path on subsequent runs. Content comparison is
    skipped because mtime preservation is sufficient when curate is the
    sole writer."""
    if dst.exists():
        try:
            ssz = src.stat().st_size
            smt = src.stat().st_mtime
            dsz = dst.stat().st_size
            dmt = dst.stat().st_mtime
            # 1-second granularity tolerance for FS that floor mtime.
            if ssz == dsz and abs(smt - dmt) < 1.0:
                stats.unchanged += 1
                return
            # Size differs OR mtime differs significantly — re-copy.
            if not dry_run:
                shutil.copy2(src, dst)
            stats.modified.append(rel_label)
            return
        except OSError:
            # Fall through to full copy on any stat error.
            pass
    if not dry_run:
        _ensure_dir(dst.parent)
        shutil.copy2(src, dst)
    stats.added.append(rel_label)


def _walk_files(root: Path) -> Iterable[Path]:
    """Walk `root` recursively, skipping anything under a `.git` directory.

    Sorted output for stable iteration across runs."""
    for dirpath, dirnames, filenames in os.walk(root):
        # Skip .git directories defensively (Github/ may have its own .git
        # once the push layer initialises it; we MUST NOT touch that tree).
        dirnames[:] = sorted(d for d in dirnames if d != ".git")
        for fn in sorted(filenames):
            yield Path(dirpath) / fn


# ---------------------------------------------------------------------
# Section B. Auto-generated files
# ---------------------------------------------------------------------
def _read_first_paragraph(p: Path) -> str:
    """Read first non-frontmatter paragraph of a markdown file."""
    if not p.exists():
        return ""
    text = p.read_text(encoding="utf-8", errors="replace")
    # Strip frontmatter
    text = re.sub(r"^---\n.*?\n---\n", "", text, count=1, flags=re.DOTALL)
    paragraphs = [s.strip() for s in re.split(r"\n\s*\n", text) if s.strip()]
    return paragraphs[0] if paragraphs else ""


def _parse_top_changelog(n: int = 5) -> list[Tuple[str, str]]:
    """Return `[(date, title), ...]` for the latest `n` CHANGELOG entries."""
    if not CHANGELOG.exists():
        return []
    text = CHANGELOG.read_text(encoding="utf-8", errors="replace")
    # CHANGELOG format observed: ## [title] — YYYY-MM-DD
    # Be lenient: also accept the alt form "## YYYY-MM-DD title".
    pat_a = re.compile(r"^##\s+\[(.+?)\]\s*[—\-]\s*(\d{4}-\d{2}-\d{2})\s*$",
                       re.MULTILINE)
    pat_b = re.compile(r"^##\s+(\d{4}-\d{2}-\d{2})\s+(.+)$", re.MULTILINE)
    out = []
    for m in pat_a.finditer(text):
        title = m.group(1).strip()
        date = m.group(2).strip()
        out.append((date, title))
        if len(out) >= n:
            return out
    if not out:
        for m in pat_b.finditer(text):
            out.append((m.group(1), m.group(2).strip()))
            if len(out) >= n:
                return out
    return out


def _parse_scorecard_summary() -> str:
    """Return a one-line scorecard summary from CLAUDE.md Section 8 if present."""
    claude = REPO_ROOT / "CLAUDE.md"
    if not claude.exists():
        return ""
    text = claude.read_text(encoding="utf-8", errors="replace")
    # Find Stage-1 scorecard summary line
    m = re.search(r"Stage-1 scorecard summary[^.]*\.([^.]+)\.", text)
    if m:
        return m.group(0).strip()
    return ""


def _render_cross_framework_comparison_md() -> str:
    """The compact cross-framework comparison table (mirrored from
    `Website/data/status.js` "Side-by-side comparison vs other frameworks
    (compact)" card) in GitHub-flavoured Markdown.

    Rendered as a single Markdown table with bold-tagged status verdicts
    (GitHub README has no CSS, so the website's <span class="tag tag-ok"
    /> elements collapse to bold-text equivalents). Math expressions use
    GFM `$...$` inline-math syntax (supported since 2022).
    """
    out = "## Side-by-side comparison vs other frameworks (compact)\n\n"
    out += (
        "Compact comparison of TECT against three reference frameworks: the "
        "**Standard Model (SM)**, **Superstring / M-theory**, and **Loop "
        "Quantum Gravity (LQG)**. Status reflects the publicly stated state "
        "of each programme as of 2026 spring; entries for non-TECT frameworks "
        "are summary-grade and meant for orientation, not adjudication.\n\n"
    )

    out += "| Axis | **TECT** | Standard Model | Superstring / M | Loop Quantum Gravity |\n"
    out += "|---|---|---|---|---|\n"
    out += (
        "| Foundational axioms "
        "| **2** (A0 BCC condensate with TDGL kinetics; A1 cosmological "
        "cooling history $T(t)$); Math195 "
        "| ~26 parameters + chosen gauge group + 3 generations "
        "| 5–10 (10/11-dim spacetime, branes, compactification, flux, SUSY, "
        "vacuum) "
        "| 4–5 (spin-network kinematics, holonomy/flux algebra, dynamics, "
        "semiclassical limit) "
        "|\n"
    )
    out += (
        "| Predicts SM gauge group "
        "| **PROVED CONDITIONAL** — Math80-AddA + Math162 + Math191/192: "
        "$\\mathrm{Stab}_{\\mathrm{SU}(5)}\\,\\mathrm{Gr}(2,5)=G_{\\rm SM}$ "
        "| **No** — gauge group postulated "
        "| **Partial** — landscape of vacua "
        "| **No** — gauge content imported "
        "|\n"
    )
    out += (
        "| Predicts gravity "
        "| **Yes** — emergent spin-2 graviton at 1-loop (Pillar 3 "
        "CLOSED@1-loop) "
        "| **No** "
        "| **Yes** — closed-string graviton mode "
        "| **Yes** — quantises GR by construction "
        "|\n"
    )
    out += (
        "| Predicts $\\hbar$ "
        "| **CONDITIONAL (weak)** — Math110-AddI: "
        "$\\hbar=c^{3} a_{\\rm BCC}^{2}/(16\\pi G)$ "
        "| **No** — input constant "
        "| **No** "
        "| **No** "
        "|\n"
    )
    out += (
        "| Predicts cosmological constant "
        "| **PROVED CONDITIONAL** — Math58-v7 four-sector cancellation chain "
        "(Pillar 11 NEAR-CLOSURE) "
        "| **No** "
        "| **No** — landscape predictability "
        "| **No** "
        "|\n"
    )
    out += (
        "| Quantum-consistent "
        "| **Partial** — anomaly cancellation conditional on Pillar 4; BRST "
        "FP determinant computed "
        "| **Yes** — by construction "
        "| **Yes** (perturbative) "
        "| **Partial** — kinematics yes, dynamics open "
        "|\n"
    )
    out += (
        "| Falsifiable predictions "
        "| **3 pre-registered + Kibble–Zurek GW (Math172)** "
        "| **Many** "
        "| **Few** — energies inaccessible "
        "| **Few** — kinematic mostly "
        "|\n"
    )
    out += (
        "| Empirical agreement (current) "
        "| **Partial** — classical sector agrees; cosmology rescoped to "
        "Kibble–Zurek with PROVISIONAL GW prediction "
        "| **Excellent** within scope "
        "| **Untested** "
        "| **Untested** "
        "|\n"
    )

    out += (
        "\n*Reading the table*: TECT's distinguishing claim is **axiom-level "
        "parameter compression** -- fewer foundational inputs than the listed "
        "alternatives -- purchased at the cost of an active Pillar-4 sub-task "
        "3 closure path and an open quantum-consistency closure path. The "
        "live, interactive version of this comparison (with per-cell tooltips "
        "and the live cross-framework narrative) is at "
        "[status.html](status.html) on the published site.\n\n"
    )
    return out


def render_readme() -> str:
    """Top-level README.md for the public GitHub repo (auto-generated).

    Sections (revised 2026-05-01 per operator request, two passes):
      0. Sentinel + title + last-curated date
      1. What is TECT (detailed)
      2. Foundational axioms (A0 + A1 per Math195)
      3. Key emergent results (gauge / gravity / hbar / Lambda)
      4. Cross-framework comparison (mirrored from States page card)
      5. TOE 6-Stage roadmap (canonical, mirrors toe.js card —
         construction-order: BCC → gravity → quantum gravity → ℏ →
         SM → QFT → TOE)
      6. How to navigate the repo
      7. License + maintainer

    Removed (operator request 2026-05-01): ``Recent activity (top 5
    from CHANGELOG)``, ``Support TECT research``, and ``Project tagline``
    sections. Recent activity → CHANGELOG.md + Github commit history;
    donation/funding info → live site footer (states / theory / papers /
    toe pages); tagline → GitHub repo About box (set via
    github_sync_push.py meta) which serves the one-liner role
    redundantly with the README's What is TECT detailed section.
    """
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    out = AUTO_SENTINEL_MD
    out += "# TECT -- Topological Energy Condensate Theory\n\n"
    out += f"_Last curated: {today} (UTC) -- auto-generated mirror of the "
    out += "canonical research repository._\n\n"
    out += "---\n\n"

    # ---- Section 1: What is TECT (detailed) ----
    out += "## What is TECT?\n\n"
    out += "TECT is a research programme that derives the Standard Model "
    out += "(SM) gauge structure, general relativity (GR), and the quantum "
    out += "constants of nature ($\\hbar$, $\\Lambda$) as **low-energy "
    out += "consequences of a single primordial three-dimensional "
    out += "body-centred-cubic (BCC) topological condensate** of an O(n) "
    out += "order parameter. The condensate is governed by Brazovskii-type "
    out += "free-energy dynamics; the BCC ground state breaks rotational "
    out += "symmetry to the cubic point group $O_h$ but preserves CP and "
    out += "translation. Pillar-by-pillar emergence theorems (Pillars 1–11) "
    out += "show that mass, kinematic Lorentz invariance, gravity, gauge "
    out += "structure, fermion content, Higgs mechanism, electroweak "
    out += "breaking, QCD confinement, the cosmological constant, the "
    out += "no-classical-$\\hbar$ no-go theorem, and chirality each arise "
    out += "from the same underlying lattice condensate without additional "
    out += "structural input.\n\n"
    out += "The framework is graded against an explicit **TOE qualification "
    out += "predicate** $\\mathrm{TOE} := S_1 \\wedge S_2 \\wedge S_3$ "
    out += "(per `Math60-TOE-Global-Closure-Spec`), extended below to a "
    out += "six-stage roadmap that includes cosmological extension, "
    out += "external verification, and publication acceptance. All claims "
    out += "are pinned to specific Math notes (`Docs/math/TECT-Math<NN>-*.tex.txt`) "
    out += "with explicit T0–T7 tier labels (per "
    out += "[STATUS_NOMENCLATURE.md](docs/POLICIES_INDEX.md)).\n\n"

    # ---- Section 2: Foundational axioms ----
    out += "## Foundational axioms (Math195)\n\n"
    out += "Per `TECT-Math195` (effective-axiom reduction analysis):\n\n"
    out += "- **A0** (BCC condensate dynamics): Brazovskii free energy "
    out += "$F[\\Psi] = \\int [\\frac{1}{2}|\\nabla\\Psi|^2 + \\frac{1}{2}\\mu^2|\\Psi|^2 "
    out += "+ \\frac{1}{2}\\gamma(\\Delta + q_0^2)^2|\\Psi|^2 + \\frac{1}{4}\\lambda|\\Psi|^4] "
    out += "d^3x$ governing a vector order parameter "
    out += "$\\Psi:\\mathbb{R}^3 \\to \\mathbb{C}^n$ with TDGL Model-A "
    out += "kinetics.\n"
    out += "- **A1** (cosmological cooling history): a monotone temperature "
    out += "trajectory $T(t)$ that drives the system through the BCC "
    out += "freeze-out transition (Math97 Brazovskii universality class).\n"
    out += "- **A2** (boundary condition): a Cauchy boundary condition at "
    out += "$t \\to -\\infty$, *reducible* to A0 + A1 dynamics with an "
    out += "external cosmological-evolution input. Effective core axiom "
    out += "count: **2 + 1 = 3 hierarchically structured**, with the "
    out += "two-axiom core $\\{A0, A1\\}$ load-bearing for the bulk of "
    out += "the theorem chain.\n\n"
    out += "All other inputs (gauge group, fermion generations, Higgs "
    out += "potential coefficients, $\\hbar$, $G$ at low-energy precision) "
    out += "are derived emergently rather than postulated.\n\n"

    # ---- Section 3: Key emergent results ----
    out += "## Key emergent results (theorem-level)\n\n"
    out += "| Result | Formula / mechanism | Tier | Canonical source |\n"
    out += "|---|---|---|---|\n"
    out += "| Mass gap $m^*$ | Single-mode Math56 cone, BCC ground-state uniqueness "
    out += "(Pillar 1) | T7 PROVED | `Math01-v2`, `Math82-AddG/H` |\n"
    out += "| Kinematic Lorentz | $|c_T - c|/c \\le 4.8\\times 10^{-4}$ "
    out += "(Pillar 2) | T6 PROVED CONDITIONAL | `Math_IR_Bound-v4-thm-v4-2-final` |\n"
    out += "| Emergent graviton | Spin-2 mode at 1-loop "
    out += "(Pillar 3) | T5 CLOSED@1-loop | `Pillar-3` notes |\n"
    out += "| SO(10) gauge group | $\\mathrm{Stab}_{O_h}(\\mathbf{T}_{1g}) "
    out += "\\cap \\mathrm{Stab}_{\\mathrm{SO}(10)}(\\mathbf{10}_{\\rm vec}) "
    out += "= G_{\\rm SM}$ (Pillar 4 atomic) | T6 PROVED CONDITIONAL | `Math270`, `Math279` |\n"
    out += "| Planck constant | $\\hbar_{\\rm TECT} = c^3 a_{\\rm BCC}^2/(16\\pi G)$ "
    out += "(Pillar 4 GAP-1) | T6 PROVED CONDITIONAL | `Math291` (errata for Math110-AddI) |\n"
    out += "| Cosmological constant | Four-sector cancellation "
    out += "(Pillar 11) | T6 PROVED CONDITIONAL | `Math58-v7` |\n"
    out += "| Three pre-registered | Lorentz $\\|\\kappa^{(c)}\\| \\in [1.5,5.5]\\times 10^{-4}$; "
    out += "Eötvös $\\|\\eta_{\\mathrm{EP}}\\| \\in [2,8]\\times 10^{-13}$; "
    out += "GW/CMB $Z_h \\in [0.575, 0.875]$ (Math60-E) | SEALED | `Math61-v1.0` |\n\n"

    # ---- Section 4: cross-framework comparison ----
    out += _render_cross_framework_comparison_md()
    out += "Detailed per-pillar status: [docs/KEY_RESULTS.md](docs/KEY_RESULTS.md). "
    out += "The interactive site is published at [tect.kr](https://tect.kr); "
    out += "the GitHub mirror is browsable from the repository root by "
    out += "opening `index.html` directly.\n\n"

    # ---- Section 5: TOE 6-Stage Roadmap (canonical, mirrors toe.js card) ----
    out += "## TOE — 6-Stage Roadmap (canonical, construction-order)\n\n"
    out += "The 11 emergence pillars and the $S_1 \\wedge S_2 \\wedge S_3$ "
    out += "qualification predicate are re-arranged into a **6-Stage "
    out += "roadmap** that traces the natural construction order from BCC "
    out += "condensate to TOE: classical gravity emergence → quantum "
    out += "gravity extension → $\\hbar$ generation → SM integration → "
    out += "QFT unification → TOE completion. Each Stage groups multiple "
    out += "Pillars and gates; status reflects the post-Math310 (Turn 80, "
    out += "2026-05-01) state with the AUDIT-2026-05-01-Math310-N16-Wording "
    out += "correction applied. This 6-Stage view is the canonical "
    out += "presentational re-mapping mirrored from "
    out += "[toe.html](toe.html) on the live site.\n\n"
    out += "| Stage | Goal | Pillars / gates included | Status (2026-05-01) | Anchor results |\n"
    out += "|---|---|---|---|---|\n"
    out += "| **1** | Classical gravity emergence (BCC → GR) | "
    out += "Pillar 3 (gravity), 8 (Lorentz), 9 (EP), 2 (inertia/IR bound) | "
    out += "**COMPLETED ✓** (3+8+9 PROVED, 2 PROVED CONDITIONAL) | "
    out += "Math41/45/46c ($\\kappa_G^2 = Y q_0^2$, TT-purity); "
    out += "Math110-AddH ($c_T = c$); Math_IR_Bound-v4 (interval cert "
    out += "$J_1 \\in [+5.99\\!\\times\\!10^{-2}, +1.51\\!\\times\\!10^{-1}]$); "
    out += "Math_EP-rigorous-v3.1 (MPD bound) |\n"
    out += "| **2** | Quantum gravity extension (1-loop and beyond) | "
    out += "Pillar 3 multi-loop, 7 (per-gen consistency), GAP-2 (BRST) | "
    out += "**PARTIAL-ADVANCED → STRONGER post-R7-8** (1-loop CLOSED; "
    out += "GAP-2 promoted to T6 PROVED CONDITIONAL via Math280; 2-loop "
    out += "+ non-perturbative OUTLINE) | Math60-C-AddD (3 quantum "
    out += "observables QO1-3 closed form); Math120-125 (asymptotic-safety "
    out += "OUTLINE); Math160 + Math280 (BRST FP determinant T6 PROVED "
    out += "CONDITIONAL on Pillar 4 H1.1); Math47-48 (Ward); Math49b/c-v3 "
    out += "(Witten + mod-2 spectral flow) |\n"
    out += "| **3** | Planck constant ($\\hbar$) generation | "
    out += "Pillar 10 ($\\hbar$ origin), GAP-1 ($\\hbar$ matching) | "
    out += "**PARTIAL-ADVANCED → STRONGER post-Math291** (master formula "
    out += "RECONCILED to canonical Formula B; matter-side substantiated; "
    out += "GAP-1 = T4 with explicit T6 promotion path via Math299 joint "
    out += "event) | Math79-AddB (classical no-go theorem); Math98-AddA-E "
    out += "(KZ quench, Volovik shell, Berry, Onsager-Machlup); **Math291** "
    out += "(corrected master $\\hbar_{\\rm TECT} = c^3 a_{\\rm BCC}^2/(16\\pi G)$, "
    out += "Formula A errata); Math163 (boson-loop subdominance "
    out += "$R \\approx 0.12$); Math296 ($\\gamma_\\hbar^{(1)}$ first-principles); "
    out += "Math297 (continuum-limit error budget); Math298 (3-sector "
    out += "decomposition); Math299 (joint-event T4 → T6 condition) |\n"
    out += "| **4** | Standard Model integration (SM + GUT) | "
    out += "Pillars 4 (gauge), 5 (chirality), 6 (Higgs), 7 (per-gen "
    out += "consistency), 11 ($\\Lambda$); GAP-3 (anomaly) | "
    out += "**NEAR-CLOSURE post-R8 + 20-turn defence (Math270-310)** "
    out += "(Pillar 4 atomic = T6 PROVED CONDITIONAL via Math270 + Math279; "
    out += "Math302 $H_{\\rm task}$ carve-out two-component record; "
    out += "GAP-3 = T6 PROVED CONDITIONAL via Math281; Pillar 6 first "
    out += "$\\Delta F < 0$ broken-energy data point achieved at "
    out += "N=16, Math292 $\\mathcal A_{\\rm valid}$ pending transverse "
    out += "projection per Math310-AddA) | Math80-AddA + Math162 + "
    out += "Math191/192 (Pillar 4 sub-task 1 + 2 PROVED CONDITIONAL); "
    out += "Math157 + Math281 (SO(10) $\\mathbf{16}$ anomaly six "
    out += "coefficients exact zero); Math229 (sub-task 3 Cartan "
    out += "forcing); Math242 (cubic-sublattice ladder); Math270 + Math279 "
    out += "(atomic defence + final restatement); Math305 ($\\Sigma_0$ "
    out += "Cech atlas); Math288 + Math300 (defect-mass "
    out += "F-GAP4-DEFECT-MASS verdict template); Math58-v7 (Pillar 11 "
    out += "$\\Lambda$ four-sector cancellation); Math10-14 (chirality) |\n"
    out += "| **5** | Quantisation and QFT unification | "
    out += "Pillar 1 (mass gap), Stage-2 Math60-A..E sub-theorems, "
    out += "GAP-1/2/3/4 collectively | **PARTIAL → STRENGTHENED post-R8** "
    out += "(5/5 Math60 sub-theorems SEALED; 3/4 quantum gates promoted "
    out += "to T6 PROVED CONDITIONAL; Stage-2 composite = T3 PROOF "
    out += "SKETCH via min-rule; T6 promotion gated on Math307 joint "
    out += "event) | Math82-AddF (Pillar 1 numerical anchor "
    out += "$m^{*2}_{\\rm num} = +4.247\\!\\times\\!10^{-2}$); Math60-A "
    out += "meta-consistency (Math83); Math60-B parameter compression "
    out += "$4.75\\times$ vs SM 19; Math60-C-AddD QO1-3 closed form; "
    out += "Math60-D global injectivity; Math60-E falsifiability "
    out += "(3 pre-registered + Math172); Math292 (4-gauge acceptance "
    out += "criterion); Math293 (3-class false-negative taxonomy); "
    out += "Math301 (min-rule explanatory); Math307 (Stage-2 promotion "
    out += "path) |\n"
    out += "| **6** | TOE completion ($S_1 \\wedge S_2 \\wedge S_3$ "
    out += "unconditional) | All 11 Pillars + S1, S2, S3 final closure | "
    out += "**PARTIAL → on track** (theoretical layer ACHIEVABLE in "
    out += "remaining Phase 8-14 of next 20-turn arc Math311-330; "
    out += "phenomenological layer gated on SKA / IPTA-2 2028-2030) | "
    out += "Math60 spec ($\\mathrm{TOE} := S_1 \\wedge S_2 \\wedge S_3$); "
    out += "Math193 (self-containment 3-layer analysis); Math195 (A2 axiom "
    out += "reduction → effective **2-axiom theory**: 1 physics + 1 "
    out += "cosmological); Math190 + Math269 + Math289 + Math310 "
    out += "(autonomous-arc final syntheses); Math172 + Math196 "
    out += "(Stage-3 PROVISIONAL prediction $\\Omega_{\\rm GW} \\sim 10^{-15}$ "
    out += "at PTA, observable by SKA / IPTA-2 2028-2030); "
    out += "[`docs/PHASE_8_TO_14_PLAN.md`](docs/PHASE_8_TO_14_PLAN.md) "
    out += "(next-20-turn closure roadmap) |\n\n"
    out += "**Effective axiom count post-Math195**: TECT = **1 physics "
    out += "axiom (A0 BCC condensate) + 1 cosmological axiom (cooling "
    out += "$T(t)$)**. Comparable to Einstein GR (1-2 + 1-2 = 2-4); "
    out += "strictly fewer than SM (~7), LQG (~5-6), String/M (~6-11).\n\n"
    out += "**One-glance synthesis**: Stages 1-4 are well-advanced "
    out += "(1 COMPLETED ✓, 2/3 PARTIAL-ADVANCED-STRONGER, 4 NEAR-CLOSURE "
    out += "with two-component (T6, realization PENDING) record). Stage 5 "
    out += "is PARTIAL but reducible (Stage-2 composite T3 → T6 promotion "
    out += "via Math307 joint event). Stage 6 (final TOE qualification) "
    out += "is on a clear trajectory: theoretical-layer self-completion "
    out += "ACHIEVABLE in 20 more autonomous turns (Math311-330, see "
    out += "[`docs/PHASE_8_TO_14_PLAN.md`](docs/PHASE_8_TO_14_PLAN.md)); "
    out += "phenomenological-layer self-completion gated on SKA "
    out += "(calendar-dependent, not mathematics-dependent). The five "
    out += "active falsification gates carry hard deadlines spanning "
    out += "2026-05-14 to 05-29 and pre-registered failure-mode "
    out += "taxonomies.\n\n"

    # ---- Section 6: navigation ----
    out += "## How to navigate this repository\n\n"
    out += "- `index.html` — landing page (also navigable: `theory.html`, "
    out += "`status.html`, `papers.html`, `toe.html`, `results.html`, "
    out += "`history.html`, `records.html`, `math-notes.html`, `code.html`).\n"
    out += "- `data/` — the live JavaScript data layer that the pages render.\n"
    out += "- `assets/` — math notes (`assets/math/TECT-Math*.tex.txt`), code "
    out += "mirror (`assets/code/`), policy snapshots, asset manifest.\n"
    out += "- `docs/` — curated standalone documents: KEY_RESULTS, NAVIGATION, "
    out += "POLICIES_INDEX.\n"
    out += "- `CHANGELOG.md` — full chronological change log (root of the "
    out += "main repository; mirrors are auto-generated from this file).\n"
    out += "- `CITATION.cff` — citation metadata (auto-generated).\n\n"
    out += "All artefacts in this repository are written in English per the "
    out += "[output-language policy](docs/POLICIES_INDEX.md).\n\n"

    # ---- Section 7: license + maintainer ----
    out += "## License & maintainer\n\n"
    out += "- License: **Creative Commons Attribution 4.0 International "
    out += "(CC BY 4.0)** -- see `LICENSE` for the verbatim legal code "
    out += "and the required attribution string. SPDX: `CC-BY-4.0`.\n"
    out += "- Maintainer: Jusang Lee (`jtkor@outlook.com`).\n"
    out += "- Issues / contributions: open an Issue on GitHub or contact via email.\n"
    out += "- Citation: see `CITATION.cff`.\n"
    return out


def render_citation_cff() -> str:
    """CITATION.cff (Citation File Format v1.2.0) auto-generated stub.

    Operator should hand-edit DOI / preferred-citation once a paper lands."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    out = AUTO_SENTINEL_YAML
    out += 'cff-version: "1.2.0"\n'
    out += 'message: "If you use TECT theory or its accompanying numerical "\n'
    out += '         "artefacts in academic work, please cite the canonical "\n'
    out += '         "repository as below until a published manuscript is "\n'
    out += '         "available."\n'
    out += "type: software\n"
    out += 'title: "TECT — Topological Energy Condensate Theory"\n'
    out += 'authors:\n'
    out += '  - family-names: "Lee"\n'
    out += '    given-names: "Jusang"\n'
    out += '    email: "jtkor@outlook.com"\n'
    out += f'date-released: "{today}"\n'
    out += 'repository-code: "https://github.com/TECT-OpenPhysics/TECT"\n'
    out += 'license: "CC-BY-4.0"\n'
    out += "keywords:\n"
    out += '  - "theoretical physics"\n'
    out += '  - "topological condensate"\n'
    out += '  - "BCC lattice"\n'
    out += '  - "Brazovskii"\n'
    out += '  - "grand unified theory"\n'
    out += '  - "theory of everything"\n'
    return out


LICENSE_TEMPLATE_PATH = (
    Path(__file__).resolve().parent / "templates" / "LICENSE-CC-BY-4.0.txt"
)


def render_license() -> str:
    """LICENSE = short TECT attribution header + verbatim CC BY 4.0 legal code.

    Reads the official Creative Commons CC BY 4.0 legal code from
    Codes/tools/templates/LICENSE-CC-BY-4.0.txt (downloaded once from
    https://creativecommons.org/licenses/by/4.0/legalcode.txt). The legal
    code is reproduced verbatim -- DO NOT modify the template file.

    The attribution header documents licensor, work title, year, contact
    -- the information a downstream user needs to comply with the BY
    (attribution) clause s3.a.1 of the licence.
    """
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    if not LICENSE_TEMPLATE_PATH.exists():
        raise FileNotFoundError(
            "CC BY 4.0 template not found at " + str(LICENSE_TEMPLATE_PATH)
            + ". Download via: Invoke-WebRequest -Uri "
              "'https://creativecommons.org/licenses/by/4.0/legalcode.txt' "
              "-OutFile '" + str(LICENSE_TEMPLATE_PATH) + "'"
        )

    legal_code = LICENSE_TEMPLATE_PATH.read_text(encoding="utf-8")

    header = (
        "TECT -- Topological Energy Condensate Theory\n"
        "============================================\n"
        "\n"
        "Copyright (c) 2026 Jusang Lee <jtkor@outlook.com>.\n"
        "\n"
        "This work (the \"TECT\" repository, including all text, figures,\n"
        "mathematical notes, code, and accompanying documentation) is\n"
        "licensed under the Creative Commons Attribution 4.0 International\n"
        "License (CC BY 4.0). To view a copy of this license, visit\n"
        "https://creativecommons.org/licenses/by/4.0/ or read the verbatim\n"
        "legal code reproduced below.\n"
        "\n"
        "Required attribution (BY clause s3.a.1):\n"
        "  Author : Jusang Lee\n"
        "  Title  : TECT -- Topological Energy Condensate Theory\n"
        "  Source : https://github.com/TECT-OpenPhysics/TECT\n"
        "  License: CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/)\n"
        "\n"
        "SPDX-License-Identifier: CC-BY-4.0\n"
        "License integration date: " + today + "\n"
        "\n"
        "-----------------------------------------------------------------------\n"
        " Verbatim Creative Commons Attribution 4.0 International legal code\n"
        " (downloaded from https://creativecommons.org/licenses/by/4.0/legalcode.txt;\n"
        "  reproduced unchanged)\n"
        "-----------------------------------------------------------------------\n"
        "\n"
    )

    return header + legal_code


def render_gitignore_for_target() -> str:
    """The .gitignore that ships INSIDE Github/ for the public repo."""
    out = "# .gitignore for the public TECT mirror.\n"
    out += "# Curated by Codes/tools/github_sync_curate.py.\n\n"
    out += "# OS / editor noise\n"
    out += ".DS_Store\nThumbs.db\n.vscode/\n.idea/\n*.swp\n\n"
    out += "# Python build artefacts (the mirror does not build Python here, "
    out += "but the assets/code/ subtree includes .py files which should be "
    out += "treated as plain text — not compiled).\n"
    out += "__pycache__/\n*.pyc\n\n"
    out += "# Local environment\n"
    out += ".env\n.env.*\n!.env.example\n"
    return out


def render_nojekyll() -> str:
    """`.nojekyll` empty file: instructs GitHub Pages NOT to run Jekyll, so
    that paths like `data/_archive/` (leading underscore) are served as-is."""
    return ""


def render_key_results() -> str:
    """docs/KEY_RESULTS.md — pillar scorecard snapshot."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    out = AUTO_SENTINEL_MD
    out += f"# TECT — Key Results (snapshot {today})\n\n"
    out += "This is a static snapshot of the live scorecard. The authoritative "
    out += "source is `Docs/status/TOE-FACT-SHEET.md` in the canonical "
    out += "repository; this file is regenerated from the website state on "
    out += "every `github_sync_curate.py` run.\n\n"
    if LATEST_STATUS.exists():
        out += "## Latest status banner (mirrored from website footer)\n\n"
        out += LATEST_STATUS.read_text(encoding="utf-8", errors="replace") + "\n\n"
    if TOE_FACT_SHEET.exists():
        out += "## TOE-FACT-SHEET excerpt (Stage-1 scorecard rows)\n\n"
        text = TOE_FACT_SHEET.read_text(encoding="utf-8", errors="replace")
        # Pull a Stage-1 / Stage 1 / Pillar table block. Heuristic: take the
        # first markdown table after the first heading containing 'Stage 1'
        # or 'Pillar'. If absent, fall back to the first table.
        m = re.search(r"^(## .*Stage[- ]?1.*)$", text, re.MULTILINE | re.IGNORECASE)
        if not m:
            m = re.search(r"^(## .*Pillar.*)$", text, re.MULTILINE | re.IGNORECASE)
        if m:
            tail = text[m.start():]
            tbl = re.search(r"(\|.+\|\n\|[\s:|-]+\|\n(?:\|.+\|\n)+)", tail)
            if tbl:
                out += tbl.group(1) + "\n"
        else:
            out += "_(table extraction failed; see canonical TOE-FACT-SHEET.md)_\n"
    else:
        out += "_(TOE-FACT-SHEET.md not present in canonical repository)_\n"
    return out


def render_navigation() -> str:
    """docs/NAVIGATION.md — cross-reference map for the public mirror."""
    out = AUTO_SENTINEL_MD
    out += "# Repository navigation\n\n"
    out += "## Live site\n\n"
    out += "Open any `*.html` file at the repository root, or visit the GitHub "
    out += "Pages URL once Pages is enabled. Pages:\n\n"
    out += "| Page | Source | Purpose |\n|---|---|---|\n"
    out += "| `index.html` | `data/index.js` | Landing + executive summary |\n"
    out += "| `theory.html` | `data/theory.js` | Theory overview, axioms, stage hierarchy |\n"
    out += "| `status.html` | `data/status.js` | TECT-Status-Tier (T0–T7) per-pillar scorecard |\n"
    out += "| `papers.html` | `data/papers.js` | Manuscript / paper drafts |\n"
    out += "| `toe.html` | `data/toe.js` | TOE candidate cross-framework comparison |\n"
    out += "| `results.html` | `data/results.js` | Numerical results inventory + Honest-status table |\n"
    out += "| `history.html` (+ pages 2–7) | `data/history.js` | CHANGELOG-driven activity log |\n"
    out += "| `records.html` | `data/records.js` | Active OPEN questions + retracted negative results |\n"
    out += "| `math-notes.html` | `data/math-notes.js` | All Math notes index |\n"
    out += "| `code.html` | `data/code.js` | Live code inventory with Purpose column |\n"
    out += "| `code-old.html` | `data/code-old.js` | Older code versions for reproducibility |\n\n"
    out += "## Asset structure\n\n"
    out += "- `assets/math/TECT-Math*.tex.txt` — every Math note in plain LaTeX-text form.\n"
    out += "- `assets/code/{pde,tools,supplementary,scripts,tests}/` — code mirror.\n"
    out += "- `assets/manifest.json` — full asset manifest (path, size, mtime).\n"
    out += "- `assets/CHANGELOG.md`, `assets/CLAUDE.md`, `assets/NAVIGATION.md` — "
    out += "snapshots of the canonical repository's top-level documents.\n\n"
    out += "## Curated docs (this folder)\n\n"
    out += "- `KEY_RESULTS.md` — pillar scorecard snapshot.\n"
    out += "- `NAVIGATION.md` — this file.\n"
    out += "- `POLICIES_INDEX.md` — index of binding repository policies.\n"
    return out


def render_policies_index() -> str:
    """docs/POLICIES_INDEX.md — binding policies summary."""
    out = AUTO_SENTINEL_MD
    out += "# Binding policies (index)\n\n"
    out += "TECT operates under a small set of explicit, binding policies "
    out += "documented in the canonical repository at `Docs/policy/`. The "
    out += "most operationally important ones are listed here for the "
    out += "external reader.\n\n"
    policy_dir = REPO_ROOT / "Docs" / "policy"
    if policy_dir.exists():
        out += "| Policy | Summary |\n|---|---|\n"
        for fp in sorted(policy_dir.glob("*.md")):
            title_line = ""
            try:
                with fp.open(encoding="utf-8", errors="replace") as fh:
                    for line in fh:
                        line = line.strip()
                        if line.startswith("# "):
                            title_line = line[2:].strip()
                            break
            except OSError:
                continue
            if not title_line:
                title_line = fp.stem.replace("_", " ")
            out += f"| `{fp.name}` | {title_line} |\n"
    else:
        out += "_(Docs/policy/ not present in canonical repository)_\n"
    return out


# ---------------------------------------------------------------------
# Section C. Verbatim copies of website tree
# ---------------------------------------------------------------------
def copy_website_tree(stats: CurateStats, *, dry_run: bool) -> None:
    """Mirror Website/*.html, Website/data/, Website/assets/ into Github/.

    The mirror is a *flat* copy of Website/ contents (so that
    `index.html` lives at the repository root, which is what GitHub
    Pages expects)."""
    if not WEBSITE.exists():
        return

    # 1) Top-level *.html files
    for html in sorted(WEBSITE.glob("*.html")):
        rel = html.name
        _copy_file_idempotent(html, TARGET / rel, stats, rel, dry_run=dry_run)

    # 2) data/ subtree (everything: .js, .json, _archive/, _narrative/)
    src_data = WEBSITE / "data"
    dst_data = TARGET / "data"
    for fp in _walk_files(src_data):
        rel = fp.relative_to(WEBSITE).as_posix()
        _copy_file_idempotent(fp, TARGET / rel, stats, rel, dry_run=dry_run)

    # 3) assets/ subtree (math notes, code mirror, manifest, top-level
    #    document snapshots like CHANGELOG.md / CLAUDE.md)
    src_assets = WEBSITE / "assets"
    if src_assets.exists():
        for fp in _walk_files(src_assets):
            rel = fp.relative_to(WEBSITE).as_posix()
            _copy_file_idempotent(fp, TARGET / rel, stats, rel, dry_run=dry_run)


# ---------------------------------------------------------------------
# Section D. Removal of stale targets
# ---------------------------------------------------------------------
def prune_stale_files(stats: CurateStats, *, dry_run: bool) -> None:
    """Remove files in Github/ that no longer have a source counterpart.

    Excluded from removal:
      - .git/ subtree (push layer territory)
      - Github/LICENSE, Github/.gitignore, Github/.nojekyll (handled
        specially: written once unless missing)
      - Anything matching an explicit operator-edited sentinel? — we
        intentionally do NOT honour such a sentinel for now to keep the
        mirror reproducible. The operator MUST treat Github/ as a
        regenerable working tree.
    """
    if not TARGET.exists():
        return

    # v1.1 (2026-05-07): operator-curated exclusions from mirror.json.
    # Files here are explicitly removed from Github/ on every curate, even
    # if they exist in Website/. Empty list = current (pre-v1.1) behaviour.
    mirror_excludes = set(_load_mirror_excludes())
    if mirror_excludes:
        # Translate "Website/assets/policy/X.md" to the Github-relative
        # path "assets/policy/X.md" (curate strips the "Website/" prefix
        # when copying — see copy_website_tree).
        translated = set()
        for src_path in mirror_excludes:
            if src_path.startswith("Website/"):
                translated.add(src_path[len("Website/"):])
            else:
                translated.add(src_path)
        mirror_excludes = translated

    # Build the set of expected target paths.
    expected: set[str] = set()
    # 1) Auto-generated top-level files
    for name in ("README.md", "CITATION.cff", "LICENSE", ".gitignore",
                 ".nojekyll"):
        expected.add(name)
    # 2) Auto-generated docs/
    for name in ("KEY_RESULTS.md", "NAVIGATION.md", "POLICIES_INDEX.md"):
        expected.add(f"docs/{name}")
    # 3) Mirrored Website/*.html
    if WEBSITE.exists():
        for html in WEBSITE.glob("*.html"):
            expected.add(html.name)
        for sub in ("data", "assets"):
            src = WEBSITE / sub
            if src.exists():
                for fp in _walk_files(src):
                    expected.add(fp.relative_to(WEBSITE).as_posix())

    # Walk Github/ and remove anything not in `expected` OR matching the
    # operator-curated exclude list (v1.1).
    for fp in _walk_files(TARGET):
        rel = fp.relative_to(TARGET).as_posix()
        if rel not in expected or rel in mirror_excludes:
            stats.removed.append(rel)
            if not dry_run:
                try:
                    fp.unlink()
                except OSError:
                    pass

    # Clean up empty directories left behind (post-removal).
    if not dry_run:
        for dirpath, dirnames, filenames in os.walk(TARGET, topdown=False):
            if Path(dirpath).name == ".git":
                continue
            if not dirnames and not filenames:
                # Don't remove the root TARGET itself.
                if Path(dirpath) == TARGET:
                    continue
                try:
                    Path(dirpath).rmdir()
                except OSError:
                    pass


# ---------------------------------------------------------------------
# Section E. Top-level orchestration
# ---------------------------------------------------------------------
# ---------------------------------------------------------------------
# Section C2. Mirror v2 framework (Math353 ACCEPTED 2026-05-07; B-beta)
# ---------------------------------------------------------------------
# These functions implement the directory-rename + content-path-rewrite
# layer planned by Math353. They are INACTIVE on the v0_compat default
# (mirror.json::v0_compat_disable_renames=true). When the operator flips
# the toggle (B-delta, next session), the curate() flow dispatches to v2
# paths. In B-beta (this session), only the --mirror-v2-preview CLI flag
# exercises v2, and only in dry-run preview-log mode (no Github/ writes).
# ---------------------------------------------------------------------

def _load_mirror_v2_config() -> dict:
    """Load the v2 fields from Codes/config/mirror.json.

    Returns a dict with v2 directives. All fields default to the safe
    v0-compat behaviour if the JSON is missing, malformed, or
    schema_version < 2.
    """
    default = {
        "v0_compat": True,
        "renames": {},
        "rewrites": [],
        "rewrite_exts": [],
        "page_serve_root": "site/",
    }
    if not MIRROR_CONFIG.exists():
        return default
    try:
        cfg = json.loads(MIRROR_CONFIG.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return default
    if int(cfg.get("schema_version", 0)) < 2:
        return default
    return {
        "v0_compat": bool(cfg.get("v0_compat_disable_renames", True)),
        "renames": dict(cfg.get("directory_renames", {}).get("rules", {})),
        "rewrites": list(cfg.get("content_path_rewrites", {}).get("rules", [])),
        "rewrite_exts": list(cfg.get("content_path_rewrites", {}).get("in_extensions", [])),
        "page_serve_root": cfg.get("page_serve_root", {}).get("v2_post_cutover", "site/"),
    }


def _apply_directory_rename(local_rel: str, renames: dict) -> str:
    """Map a local-tree relative POSIX path to the mirror-tree path.

    Longest-prefix-first match. Returns input unchanged if no rule applies.
    A rule 'Codes' -> 'code' rewrites prefix only at directory boundaries
    (so 'CodesBackup/x' is NOT matched, only 'Codes/x' or exactly 'Codes').
    """
    if not renames:
        return local_rel
    norm = local_rel.replace("\\", "/")
    sorted_keys = sorted(renames.keys(), key=lambda k: -len(k))
    for k in sorted_keys:
        bare = k.rstrip("/")
        prefix = bare + "/"
        if norm == bare:
            return renames[k].rstrip("/")
        if norm.startswith(prefix):
            tail = norm[len(prefix):]
            new_prefix = renames[k].rstrip("/")
            return f"{new_prefix}/{tail}" if tail else new_prefix
    return norm


def _apply_content_rewrites(text: str, rules: list) -> Tuple[str, int]:
    """Apply each (pattern, replacement) regex in order. Returns (new_text, n_total)."""
    total = 0
    out = text
    for r in rules or []:
        if not isinstance(r, dict):
            continue
        pat = r.get("pattern", "")
        rep = r.get("replacement", "")
        if not pat:
            continue
        try:
            new_out, n = re.subn(pat, rep, out)
        except re.error:
            continue
        total += n
        out = new_out
    return out, total


def emit_v2_preview(mirror_cfg: dict, sources: list, log_path: Path) -> dict:
    """Walk each source root, simulate v2 rename+rewrite, write preview log.

    Performs NO write to Github/. Reads source files only (to count
    rewrites). Writes only to `log_path`. Returns summary dict.
    """
    renames = mirror_cfg["renames"]
    rules = mirror_cfg["rewrites"]
    exts = set(mirror_cfg["rewrite_exts"])

    lines = [
        "# Mirror v2 rewrite preview (DRY-RUN ONLY)",
        f"# Generated: {datetime.now(timezone.utc).isoformat()}",
        f"# Math353 B-gamma; mirror.json::v0_compat_disable_renames = {mirror_cfg['v0_compat']}",
        "# Format: <local_path>  ->  <mirror_path>  |  <N rewrites>  (-1 = unreadable)",
        "",
    ]
    n_files = 0
    n_renamed = 0
    n_rewrites_total = 0
    n_unreadable = 0

    for src_root in sources:
        if not src_root.exists():
            continue
        for fp in _walk_files(src_root):
            try:
                local_rel = fp.relative_to(REPO_ROOT).as_posix()
            except ValueError:
                continue
            mirror_rel = _apply_directory_rename(local_rel, renames)
            n_files += 1
            if mirror_rel != local_rel:
                n_renamed += 1
            n_rewrites = 0
            if any(local_rel.endswith(e) for e in exts):
                try:
                    text = fp.read_text(encoding="utf-8")
                    _, n_rewrites = _apply_content_rewrites(text, rules)
                except (OSError, UnicodeDecodeError):
                    n_rewrites = -1
                    n_unreadable += 1
            if n_rewrites > 0:
                n_rewrites_total += n_rewrites
            lines.append(f"{local_rel}  ->  {mirror_rel}  |  {n_rewrites}")

    log_path.parent.mkdir(parents=True, exist_ok=True)
    log_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    return {
        "files": n_files,
        "renamed": n_renamed,
        "rewrites_total": n_rewrites_total,
        "unreadable": n_unreadable,
        "log_path": str(log_path.relative_to(REPO_ROOT)),
    }


# ---------------------------------------------------------------------
# Section C2 end (Math353 v2 framework)
# ---------------------------------------------------------------------


def curate(args: argparse.Namespace) -> int:
    stats = CurateStats()
    dry_run = bool(args.check)

    # Math353 v2 preview short-circuit. Walks local sources, simulates
    # rename+rewrite, writes Docs/status/mirror-rewrite-preview.log,
    # exits 0. No Github/ writes. Safe regardless of toggle state.
    if getattr(args, "mirror_v2_preview", False):
        mirror_cfg = _load_mirror_v2_config()
        sources = [
            REPO_ROOT / "Codes",
            REPO_ROOT / "Docs",
            REPO_ROOT / "Runs",
            REPO_ROOT / "Website",
        ]
        log_path = REPO_ROOT / "Docs" / "status" / "mirror-rewrite-preview.log"
        summary = emit_v2_preview(mirror_cfg, sources, log_path)
        print("=" * 60)
        print(" Math353 v2 mirror preview (DRY-RUN)")
        print("=" * 60)
        print(f"  Files scanned   : {summary['files']}")
        print(f"  Renamed (path)  : {summary['renamed']}")
        print(f"  Content rewrites: {summary['rewrites_total']}")
        print(f"  Unreadable      : {summary['unreadable']}")
        print(f"  Toggle (v0_compat_disable_renames) = {mirror_cfg['v0_compat']}")
        print(f"  Log: {summary['log_path']}")
        print()
        print("This is a preview only; Github/ was NOT modified.")
        return 0

    # Math353 safety: if operator flips toggle to false WITHOUT going
    # through the B-delta cutover review, refuse to write.
    mirror_cfg_check = _load_mirror_v2_config()
    if not mirror_cfg_check["v0_compat"] and not dry_run:
        print("[ERROR] mirror.json::v0_compat_disable_renames=false detected, "
              "but the v2 production cutover (Math353 Phase B-delta) has not "
              "yet shipped. Run --mirror-v2-preview to view the v2 effect, "
              "or restore v0_compat_disable_renames=true to proceed with v0 "
              "publish.", file=sys.stderr)
        return 9

    if args.clean and not dry_run:
        # Wipe Github/ except .git/ (which the push layer owns).
        if TARGET.exists():
            for child in sorted(TARGET.iterdir()):
                if child.name == ".git":
                    stats.skipped_dotgit += 1
                    continue
                if child.is_dir():
                    shutil.rmtree(child)
                else:
                    child.unlink()
        else:
            _ensure_dir(TARGET)

    if not TARGET.exists():
        if not dry_run:
            _ensure_dir(TARGET)
            _ensure_dir(TARGET_DOCS)

    print("=" * 60)
    print(" GitHub publish — Layer 1 (curate)")
    print(f" Source: {WEBSITE.relative_to(REPO_ROOT)}")
    print(f" Target: {TARGET.relative_to(REPO_ROOT)}/")
    if dry_run:
        print(" Mode  : DRY-RUN (no files written)")
    print("=" * 60)

    # E1) Auto-generated top-level files
    print("[1/5] README + CITATION + LICENSE + .gitignore + .nojekyll …")
    _write_text_idempotent(TARGET / "README.md", render_readme(),
                           stats, "README.md", dry_run=dry_run)
    _write_text_idempotent(TARGET / "CITATION.cff", render_citation_cff(),
                           stats, "CITATION.cff", dry_run=dry_run)
    # LICENSE: now an auto-generated artefact (CC BY 4.0 since 2026-04-29).
    # Reproducibility > operator hand-edit. The legal code lives in
    # Codes/tools/templates/LICENSE-CC-BY-4.0.txt (verbatim official text).
    _write_text_idempotent(TARGET / "LICENSE", render_license(),
                           stats, "LICENSE", dry_run=dry_run)
    _write_text_idempotent(TARGET / ".gitignore", render_gitignore_for_target(),
                           stats, ".gitignore", dry_run=dry_run)
    _write_text_idempotent(TARGET / ".nojekyll", render_nojekyll(),
                           stats, ".nojekyll", dry_run=dry_run)

    # E2) Auto-generated docs/
    print("[2/5] docs/KEY_RESULTS + NAVIGATION + POLICIES_INDEX …")
    _ensure_dir(TARGET_DOCS) if not dry_run else None
    _write_text_idempotent(TARGET_DOCS / "KEY_RESULTS.md", render_key_results(),
                           stats, "docs/KEY_RESULTS.md", dry_run=dry_run)
    _write_text_idempotent(TARGET_DOCS / "NAVIGATION.md", render_navigation(),
                           stats, "docs/NAVIGATION.md", dry_run=dry_run)
    _write_text_idempotent(TARGET_DOCS / "POLICIES_INDEX.md", render_policies_index(),
                           stats, "docs/POLICIES_INDEX.md", dry_run=dry_run)

    # E3) Mirror Website/
    print("[3/5] Mirror Website/*.html + data/ + assets/ …")
    copy_website_tree(stats, dry_run=dry_run)

    # E4) Prune stale files
    print("[4/5] Prune stale files (anything in Github/ without a source) …")
    prune_stale_files(stats, dry_run=dry_run)

    # E5) Summary
    print("[5/5] Summary")
    print()
    print(f"  Added     : {len(stats.added)}")
    print(f"  Modified  : {len(stats.modified)}")
    print(f"  Unchanged : {stats.unchanged}")
    print(f"  Removed   : {len(stats.removed)}")
    if stats.skipped_dotgit:
        print(f"  Skipped (.git protected): {stats.skipped_dotgit}")

    if args.verbose:
        for label, items in (("Added", stats.added),
                             ("Modified", stats.modified),
                             ("Removed", stats.removed)):
            if items:
                print()
                print(f"  --- {label} ---")
                for it in items[:50]:
                    print(f"    {it}")
                if len(items) > 50:
                    print(f"    ... ({len(items) - 50} more)")

    if dry_run:
        print()
        print("DRY-RUN: no files were written. Re-run without --check to apply.")
    else:
        print()
        print("OK: Github/ is in sync with Website/ (Layer-1 contract satisfied).")
        print("Next step: run Codes/tools/github_sync_push.py once credentials")
        print("           are configured (see Docs/policy/GITHUB_SYNC_POLICY.md).")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--check", action="store_true",
                   help="dry-run: list deltas but do not write")
    p.add_argument("--clean", action="store_true",
                   help="wipe Github/ (preserving .git/) before rebuilding")
    p.add_argument("-v", "--verbose", action="store_true",
                   help="list per-file additions / modifications / removals")
    p.add_argument("--mirror-v2-preview", action="store_true",
                   help="Math353 B-gamma: dry-run v2 mirror (rename+rewrite); "
                        "emit Docs/status/mirror-rewrite-preview.log only. "
                        "Does NOT write to Github/. Safe regardless of toggle.")
    args = p.parse_args()
    return curate(args)


if __name__ == "__main__":
    sys.exit(main())
