#!/usr/bin/env python3
# =====================================================================
# sync_toe_from_status.py v1.0
#
# Status page (Website/data/status.js, hand-curated) is the single
# source of truth for the 11-pillar canonical T-tier scoreboard.
# TOE page (Website/data/toe.js, hand-curated) carries a 6-Stage
# roadmap that includes per-stage status badges; those badges drift
# when States is updated and TOE is not.
#
# This script:
#   (1) Parses Website/data/status.js for the canonical 11-pillar
#       T-tier scoreboard (the table starting "11-Pillar scoreboard
#       in canonical tiers").
#   (2) Emits Website/data/status_pillar_tiers.js as a small
#       machine-readable payload (window.TECT_STATUS_TIERS) carrying
#       the same data in JSON form.
#   (3) Patches the TOE page (toe.html) to load the tier payload AND
#       inject a "States-derived pillar tier table" card at the top of
#       the TOE page (right under the existing 6-Stage roadmap) so the
#       TOE page always shows the live States values - no more drift.
#
# The hand-curated 6-Stage narrative in toe.js is preserved as-is;
# only the auto-derived overlay is added.
#
# CLI:
#   python -u Codes/tools/sync_toe_from_status.py
#   python -u Codes/tools/sync_toe_from_status.py --check    # dry-run
#
# Exit codes:
#   0 OK; 1 status.js parse error; 2 I/O write error.
# =====================================================================
from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
STATES_JS = REPO_ROOT / "Website" / "data" / "status.js"
TIERS_JS  = REPO_ROOT / "Website" / "data" / "status_pillar_tiers.js"
TOE_HTML  = REPO_ROOT / "Website" / "toe.html"


def parse_pillar_tiers(states_text: str) -> List[Dict[str, str]]:
    """Parse the 11-pillar table from status.js."""
    # Locate the section that contains the pillar-tier table.
    section = re.search(
        r'11-Pillar scoreboard.*?</tbody>',
        states_text, re.DOTALL
    )
    if not section:
        raise ValueError("could not locate 11-Pillar scoreboard table in status.js")
    body = section.group(0)

    rows: List[Dict[str, str]] = []
    # Each pillar row: <tr><td>N</td><td>Subject</td><td>...T?...</td>...
    row_re = re.compile(
        r'<tr><td>(\d+)</td>'
        r'<td>(.*?)</td>'
        r'<td>(.*?)</td>'
        r'<td>(.*?)</td></tr>',
        re.DOTALL,
    )
    for m in row_re.finditer(body):
        pillar_num   = m.group(1).strip()
        subject_raw  = m.group(2)
        tier_raw     = m.group(3)
        cond_raw     = m.group(4)
        # Strip HTML tags
        def strip_html(s: str) -> str:
            s = re.sub(r'<[^>]+>', '', s)
            s = re.sub(r'\s+', ' ', s).strip()
            return s
        rows.append({
            "pillar":            pillar_num,
            "subject":           strip_html(subject_raw),
            "tier_html":         tier_raw.strip(),
            "tier":              strip_html(tier_raw),
            "conditional_input": strip_html(cond_raw),
        })
    if len(rows) != 11:
        print(f"[sync-toe] WARN: expected 11 pillar rows; parsed {len(rows)}",
              file=sys.stderr)
    return rows


def write_tiers_js(rows: List[Dict[str, str]], dry_run: bool = False) -> bool:
    payload = {
        "schema":    "tect-states-pillar-tiers-v1",
        "generated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source":    "Website/data/status.js (parse of 11-Pillar scoreboard table)",
        "pillars":   rows,
    }
    body = (
        "/* AUTO-GENERATED by Codes/tools/sync_toe_from_status.py - DO NOT EDIT. */\n"
        "/* Source: Website/data/status.js (11-Pillar scoreboard parsed live).   */\n"
        "/* Loaded by toe.html so the TOE page always shows live States data.    */\n"
        "window.TECT_STATUS_TIERS = "
        + json.dumps(payload, indent=2, ensure_ascii=False)
        + ";\n"
    )
    if dry_run:
        print(f"  [dry-run] would write {TIERS_JS} ({len(body)} bytes)")
        return True
    try:
        TIERS_JS.parent.mkdir(parents=True, exist_ok=True)
        TIERS_JS.write_text(body, encoding="utf-8")
        print(f"  [tiers-js] wrote {TIERS_JS.relative_to(REPO_ROOT)} "
              f"({len(rows)} pillars)")
        return True
    except OSError as exc:
        print(f"  [ERROR] tiers-js write: {exc}", file=sys.stderr)
        return False


def patch_toe_html(dry_run: bool = False) -> bool:
    """Inject (a) <script src=...status_pillar_tiers.js> and (b) the
    auto-derived overlay container + render script into toe.html."""
    text = TOE_HTML.read_text(encoding="utf-8")
    changed = False
    # (a) script tag
    if "status_pillar_tiers.js" not in text:
        text, n = re.subn(
            r'(<script src="data/toe\.js"></script>)',
            r'\1\n<script src="data/status_pillar_tiers.js"></script>',
            text, count=1
        )
        if n == 0:
            text, n = re.subn(
                r'(<script src="data/site\.js"></script>)',
                r'\1\n<script src="data/status_pillar_tiers.js"></script>',
                text, count=1
            )
        changed = changed or (n > 0)
    # (b) overlay container + render script
    overlay_marker = "<!-- TECT-AUTO-TOE-OVERLAY -->"
    if overlay_marker not in text:
        overlay_html = (
            f'\n{overlay_marker}\n'
            '<aside id="toe-states-overlay" class="wrap" '
            'style="margin-top:1.4em;border-left:4px solid #2266aa;'
            'padding:0.8em 1.0em;background:#f6faff;">'
            '<strong>States-derived 11-pillar canonical tiers</strong> '
            '(auto-synced from <a href="status.html">Status</a> page)'
            '<div id="toe-states-overlay-body"></div>'
            '</aside>\n'
            '<script>(function() {\n'
            '  if (!window.TECT_STATUS_TIERS) return;\n'
            '  var d = window.TECT_STATUS_TIERS;\n'
            '  var rows = d.pillars.map(function(p) {\n'
            '    return "<tr><td>"+p.pillar+"</td>"+\n'
            '           "<td>"+p.subject+"</td>"+\n'
            '           "<td><strong>"+p.tier+"</strong></td>"+\n'
            '           "<td>"+p.conditional_input+"</td></tr>";\n'
            '  }).join("");\n'
            '  document.getElementById("toe-states-overlay-body").innerHTML =\n'
            '    "<table class=\\"pillar-tier\\" style=\\"margin-top:0.4em\\">"+\n'
            '    "<thead><tr><th>#</th><th>Pillar</th><th>Tier</th>"+\n'
            '    "<th>Conditional inputs (if T6)</th></tr></thead>"+\n'
            '    "<tbody>"+rows+"</tbody></table>"+\n'
            '    "<p style=\\"font-size:0.85em;color:#666;margin-top:0.5em\\">"+\n'
            '    "Live snapshot of the Status page&apos;s canonical 11-pillar "+\n'
            '    "scoreboard. Generated <code>"+d.generated+"</code> by "+\n'
            '    "<code>Codes/tools/sync_toe_from_status.py</code>. "+\n'
            '    "If this differs from the 6-Stage cards above, the cards "+\n'
            '    "are stale; trust this overlay.</p>";\n'
            '})();</script>\n'
        )
        # Inject just before </main>
        text, n = re.subn(r'(</main>)', overlay_html + r'\1', text, count=1)
        changed = changed or (n > 0)
    if not changed:
        print(f"  [toe.html] already patched (no changes)")
        return True
    if dry_run:
        print(f"  [dry-run] would patch {TOE_HTML}")
        return True
    try:
        TOE_HTML.write_text(text, encoding="utf-8")
        print(f"  [toe.html] patched {TOE_HTML.relative_to(REPO_ROOT)} "
              "(overlay injected)")
        return True
    except OSError as exc:
        print(f"  [ERROR] toe.html patch: {exc}", file=sys.stderr)
        return False


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--check", action="store_true",
                   help="dry-run: print actions, do not write")
    args = p.parse_args()
    print(" TECT sync-toe-from-status v1.0")
    print(f" Source: {STATES_JS.relative_to(REPO_ROOT)}")
    print(f" Output: {TIERS_JS.relative_to(REPO_ROOT)} + patch toe.html")
    try:
        states_text = STATES_JS.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"[sync-toe] ERROR: cannot read status.js: {exc}", file=sys.stderr)
        return 1
    try:
        rows = parse_pillar_tiers(states_text)
    except ValueError as exc:
        print(f"[sync-toe] ERROR: {exc}", file=sys.stderr)
        return 1
    print(f"[sync-toe] parsed pillar rows from status.js")
    if not write_tiers_js(rows, dry_run=args.check):
        return 2
    if not patch_toe_html(dry_run=args.check):
        return 2
    print("[sync-toe] OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
