#!/usr/bin/env python3
# =====================================================================
# paper_status_impact.py v1.0 (2026-05-07)
#
# Detects which paper drafts under Docs/papers/{papers,auxiliary,top_impact,
# epochs}/ are affected by a recent Stage-1 tier change in
# Docs/status/STATUS-HISTORY.md, by cross-referencing the paper -> Math-note
# dependency map (Website/data/papers_math_dependencies.js, auto-generated by
# extract_paper_dependencies.py) against the Math notes cited in each
# STATUS-HISTORY entry.
#
# Output: Docs/status/paper-impact-report.md (auto-overwritten on every run).
#
# Logic:
#   For each STATUS-HISTORY entry within --since YYYY-MM-DD (or last
#   --since-days days, default 90), classified by direction arrow:
#     - REFUTATION (T0)       -> all papers citing the Math note(s)        -> REVISION REQUIRED
#     - DOWNGRADE             -> all papers citing the Math note(s)        -> REVISION REQUIRED
#     - WORDING / SPLIT       -> all papers citing the Math note(s)        -> ADVISORY
#     - UPGRADE               -> (no impact on existing papers; advisory)  -> ADVISORY
#
# Governed by Docs/policy/STATUS_PROPAGATION_POLICY.md §7.
#
# CLI:
#   python -u Codes/tools/paper_status_impact.py
#   python -u Codes/tools/paper_status_impact.py --since 2026-04-15
#   python -u Codes/tools/paper_status_impact.py --since-days 30
#   python -u Codes/tools/paper_status_impact.py --check          # exit 1 if REVISION REQUIRED non-empty
#   python -u Codes/tools/paper_status_impact.py -v               # verbose
#
# Exit codes:
#   0   OK / no revision-required (or ran without --check)
#   1   --check: REVISION REQUIRED section non-empty; snapshot pipeline
#       should block promotion until resolved
#   2   I/O or parse error
# =====================================================================
from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
HISTORY_MD = REPO_ROOT / "Docs" / "status" / "STATUS-HISTORY.md"
DEPS_JS = REPO_ROOT / "Website" / "data" / "papers_math_dependencies.js"
OUT_MD = REPO_ROOT / "Docs" / "status" / "paper-impact-report.md"

# Direction arrow classification (matches STATUS-HISTORY.md convention)
ARROW_CLASS = {
    "⬆":   "UPGRADE",
    "⬇":   "DOWNGRADE",
    "⬇⬇": "REFUTATION",
    "↺":   "WORDING",
    "↪":   "SPLIT",
}
# Action mapping: which classes go into REVISION REQUIRED vs ADVISORY
REVISION_REQUIRED_CLASSES = {"REFUTATION", "DOWNGRADE"}
ADVISORY_CLASSES = {"WORDING", "SPLIT", "UPGRADE"}

MATH_TOKEN = re.compile(
    r'\bMath\d+'
    r'(?:-?(?:Add[A-Z]\w*|v\d+|[A-Z][A-Za-z0-9]*))*'
    r'(?=[^A-Za-z\d-]|$)'
)


def load_dependencies() -> Tuple[Dict[str, List[str]], Dict[str, Dict]]:
    """Load papers_math_dependencies.js. Returns:
       (forward map: paper-stem -> [Math note keys cited],
        per-paper detail dict)."""
    text = DEPS_JS.read_text(encoding="utf-8")
    # Strip the JS wrapper to get the JSON payload
    m = re.search(r'window\.TECT_PAPERS_DEPS\s*=\s*(\{.*?\});\s*$',
                  text, re.DOTALL)
    if not m:
        raise ValueError("could not parse window.TECT_PAPERS_DEPS payload")
    payload = json.loads(m.group(1))
    forward: Dict[str, List[str]] = {}
    detail: Dict[str, Dict] = {}
    for paper in payload.get("papers", []):
        stem = paper["stem"]
        forward[stem] = paper.get("cited_math", [])
        detail[stem] = paper
    return forward, detail


def reverse_map(forward: Dict[str, List[str]]) -> Dict[str, List[str]]:
    """Math note key -> [paper stems that cite it]."""
    rev: Dict[str, List[str]] = {}
    for stem, notes in forward.items():
        for n in notes:
            rev.setdefault(n, []).append(stem)
            # Also map the bare 'MathNN' (without -AddX) so that an entry
            # citing 'Math348' also matches papers that cite 'Math348-AddA'.
            bare = re.match(r'(Math\d+)', n)
            if bare and bare.group(1) != n:
                rev.setdefault(bare.group(1), []).append(stem)
    # de-dup
    for k in rev:
        rev[k] = sorted(set(rev[k]))
    return rev


def parse_history_entries(text: str,
                            since_date: Optional[datetime] = None
                            ) -> List[Dict[str, object]]:
    """Parse STATUS-HISTORY.md entries; filter by since_date if provided."""
    pat = re.compile(
        r'### Entry (\d{4}-\d{2}-\d{2})-(\d+)\s+(.+?)\s*\n(.*?)(?=\n### Entry |\n## |\Z)',
        re.DOTALL,
    )
    out: List[Dict[str, object]] = []
    for m in pat.finditer(text):
        date_s, seq, header_rest, body = m.groups()
        try:
            d = datetime.strptime(date_s, "%Y-%m-%d").replace(tzinfo=timezone.utc)
        except ValueError:
            continue
        if since_date and d < since_date:
            continue
        # Extract direction arrow (first non-whitespace char(s))
        am = re.match(r'(\S+)', header_rest)
        arrow = am.group(1) if am else ""
        # Classify
        cls = ARROW_CLASS.get(arrow, "WORDING")
        # Math notes cited in body
        math_tokens: Set[str] = set(MATH_TOKEN.findall(body))
        # Pillar identifier
        pillar_match = re.search(r'\*\*Pillar\*\*:\s*(\d+(?:\s*[,/]\s*\d+)*)',
                                  body)
        pillar_text = pillar_match.group(1) if pillar_match else ""
        # Transition descriptor
        trans = re.search(r'\*\*Transition\*\*:\s*([^\n.]+?)(?:\.|$)',
                           body, re.MULTILINE)
        transition = trans.group(1).strip() if trans else ""
        # R-tag if present
        rtag = re.search(r'\*\*R-tag\*\*:\s*`([^`]+)`', body)
        rtag_str = rtag.group(1) if rtag else ""
        # One-line summary header
        out.append({
            "date":         date_s,
            "entry_id":     f"{date_s}-{seq}",
            "arrow":        arrow,
            "class":        cls,
            "header":       header_rest.strip(),
            "pillar_text":  pillar_text,
            "transition":   transition,
            "rtag":         rtag_str,
            "math_tokens":  sorted(math_tokens),
        })
    return out


def build_report(entries: List[Dict[str, object]],
                 forward: Dict[str, List[str]],
                 detail: Dict[str, Dict],
                 since_date: Optional[datetime],
                 verbose: bool) -> Tuple[str, int]:
    """Compose the Markdown report. Returns (text, revision_required_count)."""
    rev = reverse_map(forward)
    iso_now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines: List[str] = []
    lines.append("<!-- AUTO-GENERATED by Codes/tools/paper_status_impact.py - DO NOT EDIT. -->")
    lines.append("# Paper Status Impact Report")
    lines.append("")
    lines.append(f"Generated: `{iso_now}`")
    lines.append(f"Source: `Docs/status/STATUS-HISTORY.md` + "
                  f"`Website/data/papers_math_dependencies.js`")
    if since_date:
        lines.append(f"Window: entries since `{since_date.date().isoformat()}`")
    lines.append(f"Entries audited: {len(entries)}")
    lines.append("")

    rev_required: List[Tuple[Dict, str, List[str]]] = []
    advisory:    List[Tuple[Dict, str, List[str]]] = []

    for entry in entries:
        # Affected papers = union over math tokens cited in entry, mapped
        # to papers via reverse map (with bare-MathNN fallback).
        papers: Set[str] = set()
        for tok in entry["math_tokens"]:
            if tok in rev:
                papers.update(rev[tok])
            bare = re.match(r'(Math\d+)', tok)
            if bare and bare.group(1) in rev:
                papers.update(rev[bare.group(1)])
        affected = sorted(papers)
        cls = entry["class"]
        if not affected:
            if verbose:
                print(f"  [{cls}] {entry['entry_id']}: no papers affected")
            continue
        if cls in REVISION_REQUIRED_CLASSES:
            rev_required.append((entry, cls, affected))
        else:
            advisory.append((entry, cls, affected))

    lines.append("## Affected papers (REVISION REQUIRED)")
    lines.append("")
    if not rev_required:
        lines.append("_No papers flagged for revision in this window._")
        lines.append("")
    else:
        for entry, cls, papers in rev_required:
            arrow = entry["arrow"]
            transition = entry["transition"] or "(no transition recorded)"
            rtag = entry["rtag"] or "(no R-tag)"
            lines.append(f"### {entry['entry_id']} {arrow} [{cls}]: {transition}")
            lines.append("")
            lines.append(f"- **R-tag**: `{rtag}`")
            lines.append(f"- **Pillar(s)**: {entry['pillar_text'] or '(unspecified)'}")
            lines.append(f"- **Math note(s) cited**: "
                          + ", ".join(f"`{m}`" for m in entry["math_tokens"]))
            lines.append("")
            lines.append("| Paper | Category | Total cites | Recommended action |")
            lines.append("|---|---|---:|---|")
            for stem in papers:
                cat = detail.get(stem, {}).get("category", "?")
                total = detail.get(stem, {}).get("total", 0)
                action = ("REVISE: refuted/downgraded Math note cited; "
                           "audit affected sections, downgrade promotional "
                           "adjectives, or grandfather with [NEEDS_UPDATE] flag")
                lines.append(f"| `{stem}` | {cat} | {total} | {action} |")
            lines.append("")

    lines.append("## Advisory (manual review recommended)")
    lines.append("")
    if not advisory:
        lines.append("_No advisory items in this window._")
        lines.append("")
    else:
        for entry, cls, papers in advisory:
            arrow = entry["arrow"]
            transition = entry["transition"] or "(no transition)"
            lines.append(f"### {entry['entry_id']} {arrow} [{cls}]: {transition}")
            lines.append("")
            lines.append(f"- **Pillar(s)**: {entry['pillar_text'] or '(unspecified)'}")
            lines.append(f"- **Math note(s) cited**: "
                          + ", ".join(f"`{m}`" for m in entry["math_tokens"]))
            lines.append(f"- **Affected papers ({len(papers)})**: "
                          + ", ".join(f"`{p}`" for p in papers))
            lines.append("")

    lines.append("## Cross-references")
    lines.append("")
    lines.append("- `Docs/policy/STATUS_PROPAGATION_POLICY.md` §7 (paper-impact gate)")
    lines.append("- `Docs/policy/MATH_NOTE_AND_PAPER_DISCIPLINE.md` §3 (new-paper triggers)")
    lines.append("- `Docs/status/STATUS-HISTORY.md` (canonical tier-change ledger)")
    lines.append("- `Codes/tools/extract_paper_dependencies.py` (paper -> Math-note map source)")
    lines.append("- `Codes/tools/paper_need_assessment.py` (companion: new-paper recommendations)")
    lines.append("")
    return ("\n".join(lines) + "\n", len(rev_required))


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--since", type=str, default=None,
                   help="parse only entries on or after this YYYY-MM-DD date")
    p.add_argument("--since-days", type=int, default=90,
                   help="if --since not set, use today - N days as cutoff (default 90)")
    p.add_argument("--check", action="store_true",
                   help="exit 1 if REVISION REQUIRED section is non-empty")
    p.add_argument("-v", "--verbose", action="store_true")
    args = p.parse_args()

    if args.since:
        since_date = datetime.strptime(args.since, "%Y-%m-%d").replace(tzinfo=timezone.utc)
    else:
        since_date = datetime.now(timezone.utc) - timedelta(days=args.since_days)

    print(f" paper_status_impact v1.0")
    print(f"   Window-since: {since_date.date().isoformat()}")
    print(f"   Source: {HISTORY_MD.relative_to(REPO_ROOT)}")
    print(f"   Deps:   {DEPS_JS.relative_to(REPO_ROOT)}")

    try:
        forward, detail = load_dependencies()
    except (OSError, ValueError) as exc:
        print(f"[paper-impact] ERROR loading deps: {exc}", file=sys.stderr)
        return 2
    print(f"   Loaded {len(forward)} papers from dependency map")

    try:
        history_text = HISTORY_MD.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"[paper-impact] ERROR loading history: {exc}", file=sys.stderr)
        return 2

    entries = parse_history_entries(history_text, since_date)
    print(f"   Parsed {len(entries)} entries since {since_date.date().isoformat()}")

    report, n_rev_required = build_report(entries, forward, detail,
                                            since_date, args.verbose)

    try:
        OUT_MD.parent.mkdir(parents=True, exist_ok=True)
        OUT_MD.write_text(report, encoding="utf-8")
        print(f"   Wrote {OUT_MD.relative_to(REPO_ROOT)} ({len(report)} bytes)")
    except OSError as exc:
        print(f"[paper-impact] ERROR writing report: {exc}", file=sys.stderr)
        return 2

    print(f"[paper-impact] Summary: REVISION_REQUIRED={n_rev_required}")
    if args.check and n_rev_required > 0:
        print(f"[paper-impact] FAIL: {n_rev_required} entries require paper revision",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
